// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="workload,hls_ip_2016_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx690tffg1157-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=2243,HLS_SYN_LUT=3206}" *)

module workload (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [32:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] key;
wire   [63:0] data;
wire   [31:0] size;
reg    gmem_blk_n_AR;
wire   [0:0] ap_CS_fsm_state2;
reg    gmem_blk_n_R;
wire   [0:0] ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] exitcond7_reg_768;
wire   [0:0] ap_CS_fsm_state19;
wire   [0:0] ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter1;
reg   [0:0] exitcond_flatten_reg_840;
reg    gmem_blk_n_AW;
wire   [0:0] ap_CS_fsm_state32;
wire   [0:0] tmp_19_fu_649_p3;
reg    gmem_blk_n_W;
reg    ap_enable_reg_pp3_iter3;
reg   [0:0] exitcond_flatten8_reg_885;
reg   [0:0] ap_pipeline_reg_pp3_iter2_exitcond_flatten8_reg_885;
reg    gmem_blk_n_B;
wire   [0:0] ap_CS_fsm_state42;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [7:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
reg    gmem_BREADY;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg   [5:0] indvar_reg_275;
reg   [5:0] j_reg_286;
reg   [12:0] indvar_flatten_reg_308;
reg   [1:0] j_1_reg_319;
reg   [11:0] indvar1_reg_330;
reg   [12:0] indvar_flatten6_reg_365;
reg   [1:0] j_3_reg_376;
reg   [11:0] indvar2_reg_387;
reg   [7:0] reg_409;
reg    ap_block_state10;
reg    ap_block_state27;
reg   [31:0] size_read_reg_751;
reg   [63:0] data_read_reg_757;
reg   [63:0] gmem_addr_reg_762;
wire   [0:0] exitcond7_fu_422_p2;
reg   [0:0] ap_pipeline_reg_pp0_iter1_exitcond7_reg_768;
wire   [5:0] indvar_next_fu_428_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [4:0] tmp_fu_434_p1;
reg   [4:0] tmp_reg_777;
reg   [4:0] ap_pipeline_reg_pp0_iter1_tmp_reg_777;
wire   [0:0] exitcond5_fu_442_p2;
reg   [0:0] exitcond5_reg_782;
wire   [0:0] ap_CS_fsm_pp1_stage0;
reg   [0:0] ap_pipeline_reg_pp1_iter1_exitcond5_reg_782;
wire   [5:0] j_2_fu_448_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [63:0] tmp_6_fu_454_p1;
reg   [63:0] tmp_6_reg_791;
reg   [63:0] ap_pipeline_reg_pp1_iter1_tmp_6_reg_791;
wire   [7:0] local_key_0_q0;
reg   [7:0] local_key_0_load_reg_801;
reg    ap_enable_reg_pp1_iter1;
reg   [0:0] tmp_10_reg_806;
wire   [0:0] ap_CS_fsm_state16;
reg   [19:0] tmp_2_reg_811;
reg   [19:0] tmp_7_reg_816;
wire   [20:0] num_batches_fu_509_p3;
reg   [20:0] num_batches_reg_821;
wire   [0:0] ap_CS_fsm_state17;
wire   [19:0] i_fu_525_p2;
reg   [19:0] i_reg_829;
wire   [0:0] ap_CS_fsm_state18;
reg   [63:0] gmem_addr_1_reg_834;
wire   [0:0] tmp_8_fu_520_p2;
wire   [0:0] exitcond_flatten_fu_554_p2;
wire   [12:0] indvar_flatten_next_fu_560_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [1:0] tmp_mid2_v_v_fu_586_p3;
reg   [1:0] tmp_mid2_v_v_reg_849;
wire   [11:0] indvar_next1_fu_606_p2;
wire   [10:0] tmp_12_fu_612_p1;
reg   [10:0] tmp_12_reg_859;
reg   [10:0] ap_pipeline_reg_pp2_iter1_tmp_12_reg_859;
reg   [0:0] tmp_15_reg_864;
reg   [0:0] ap_pipeline_reg_pp2_iter1_tmp_15_reg_864;
wire   [11:0] k_fu_643_p2;
reg   [11:0] k_reg_871;
wire   [0:0] ap_CS_fsm_state30;
wire   [0:0] tmp_16_fu_635_p3;
reg    ap_sig_ioackin_gmem_AWREADY;
reg    ap_block_state32_io;
wire   [11:0] k_1_fu_657_p2;
reg   [11:0] k_1_reg_880;
wire   [0:0] exitcond_flatten8_fu_663_p2;
wire   [0:0] ap_CS_fsm_pp3_stage0;
reg    ap_sig_ioackin_gmem_WREADY;
reg    ap_block_state37_io;
reg   [0:0] ap_pipeline_reg_pp3_iter1_exitcond_flatten8_reg_885;
wire   [12:0] indvar_flatten_next7_fu_669_p2;
reg    ap_enable_reg_pp3_iter0;
wire   [1:0] tmp_30_mid2_v_v_fu_695_p3;
reg   [1:0] tmp_30_mid2_v_v_reg_894;
wire   [11:0] indvar_next2_fu_715_p2;
wire   [10:0] tmp_21_fu_721_p1;
reg   [10:0] tmp_21_reg_904;
reg   [0:0] tmp_22_reg_909;
reg   [0:0] ap_pipeline_reg_pp3_iter1_tmp_22_reg_909;
wire   [7:0] buf_load_phi_fu_744_p3;
reg   [7:0] buf_load_phi_reg_924;
wire   [0:0] ap_CS_fsm_state8;
reg    ap_enable_reg_pp0_iter2;
wire   [0:0] ap_CS_fsm_state12;
reg    ap_enable_reg_pp1_iter2;
wire   [0:0] ap_CS_fsm_state25;
reg    ap_enable_reg_pp2_iter2;
reg    ap_enable_reg_pp3_iter1;
reg    ap_enable_reg_pp3_iter2;
reg   [4:0] local_key_0_address0;
reg    local_key_0_ce0;
reg    local_key_0_we0;
reg   [4:0] local_key_1_address0;
reg    local_key_1_ce0;
reg    local_key_1_we0;
wire   [7:0] local_key_1_q0;
reg   [10:0] buf_0_address0;
reg    buf_0_ce0;
reg    buf_0_we0;
reg   [7:0] buf_0_d0;
wire   [7:0] buf_0_q0;
reg    buf_0_ce1;
reg    buf_0_we1;
wire   [7:0] buf_0_q1;
reg   [10:0] buf_1_address0;
reg    buf_1_ce0;
reg    buf_1_we0;
reg   [7:0] buf_1_d0;
wire   [7:0] buf_1_q0;
reg    buf_1_ce1;
reg    buf_1_we1;
wire   [7:0] buf_1_q1;
wire    grp_aes256_encrypt_ecb_fu_398_ap_start;
wire    grp_aes256_encrypt_ecb_fu_398_ap_done;
wire    grp_aes256_encrypt_ecb_fu_398_ap_idle;
wire    grp_aes256_encrypt_ecb_fu_398_ap_ready;
wire   [4:0] grp_aes256_encrypt_ecb_fu_398_k_address0;
wire    grp_aes256_encrypt_ecb_fu_398_k_ce0;
reg   [7:0] grp_aes256_encrypt_ecb_fu_398_k_q0;
wire   [10:0] grp_aes256_encrypt_ecb_fu_398_buf_r_address0;
wire    grp_aes256_encrypt_ecb_fu_398_buf_r_ce0;
wire    grp_aes256_encrypt_ecb_fu_398_buf_r_we0;
wire   [7:0] grp_aes256_encrypt_ecb_fu_398_buf_r_d0;
reg   [7:0] grp_aes256_encrypt_ecb_fu_398_buf_r_q0;
wire   [10:0] grp_aes256_encrypt_ecb_fu_398_buf_r_address1;
wire    grp_aes256_encrypt_ecb_fu_398_buf_r_ce1;
wire    grp_aes256_encrypt_ecb_fu_398_buf_r_we1;
wire   [7:0] grp_aes256_encrypt_ecb_fu_398_buf_r_d1;
reg   [7:0] grp_aes256_encrypt_ecb_fu_398_buf_r_q1;
reg   [11:0] grp_aes256_encrypt_ecb_fu_398_sum;
reg   [19:0] i_1_reg_297;
reg   [1:0] j_1_phi_fu_323_p4;
reg   [11:0] k_i_reg_341;
wire   [0:0] ap_CS_fsm_state31;
wire   [0:0] ap_CS_fsm_state29;
reg   [11:0] k_i1_reg_353;
wire   [0:0] ap_CS_fsm_state33;
reg   [1:0] j_3_phi_fu_380_p4;
reg    ap_reg_grp_aes256_encrypt_ecb_fu_398_ap_start;
wire   [63:0] tmp_4_fu_438_p1;
wire   [63:0] tmp_14_fu_630_p1;
wire   [63:0] tmp_18_fu_739_p1;
wire   [63:0] data4_sum_fu_543_p2;
reg    ap_reg_ioackin_gmem_ARREADY;
reg    ap_sig_ioackin_gmem_ARREADY;
reg    ap_reg_ioackin_gmem_AWREADY;
reg    ap_reg_ioackin_gmem_WREADY;
wire   [31:0] tmp_5_fu_459_p2;
wire   [31:0] p_neg_fu_472_p2;
wire   [20:0] p_lshr_cast_fu_497_p1;
wire   [20:0] p_neg_t_fu_500_p2;
wire   [20:0] p_lshr_f_cast_fu_506_p1;
wire   [20:0] i_1_cast_fu_516_p1;
wire   [31:0] tmp_s_fu_531_p3;
wire   [63:0] tmp_9_fu_539_p1;
wire   [0:0] exitcond_fu_566_p2;
wire   [1:0] j_s_fu_580_p2;
wire   [0:0] tmp_11_fu_594_p1;
wire   [11:0] indvar1_mid2_fu_572_p3;
wire   [11:0] tmp_mid2_fu_598_p3;
wire   [11:0] tmp_13_fu_616_p2;
wire   [0:0] exitcond1_fu_675_p2;
wire   [1:0] j_4_fu_689_p2;
wire   [0:0] tmp_20_fu_703_p1;
wire   [11:0] indvar2_mid2_fu_681_p3;
wire   [11:0] tmp_30_mid2_fu_707_p3;
wire   [11:0] tmp_17_fu_725_p2;
reg   [32:0] ap_NS_fsm;
reg    ap_enable_pp0;
reg    ap_enable_pp1;
reg    ap_enable_pp2;
reg    ap_enable_pp3;

// power-on initialization
initial begin
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 33'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 ap_reg_grp_aes256_encrypt_ecb_fu_398_ap_start = 1'b0;
#0 ap_reg_ioackin_gmem_ARREADY = 1'b0;
#0 ap_reg_ioackin_gmem_AWREADY = 1'b0;
#0 ap_reg_ioackin_gmem_WREADY = 1'b0;
end

workload_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
workload_control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .key(key),
    .data(data),
    .size(size)
);

workload_gmem_m_axi #(
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
workload_gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARID(1'd0),
    .I_ARLEN(gmem_ARLEN),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_addr_1_reg_834),
    .I_AWID(1'd0),
    .I_AWLEN(32'd4096),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(buf_load_phi_reg_924),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(1'd1),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

workload_local_key_0 #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
local_key_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(local_key_0_address0),
    .ce0(local_key_0_ce0),
    .we0(local_key_0_we0),
    .d0(reg_409),
    .q0(local_key_0_q0)
);

workload_local_key_0 #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
local_key_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(local_key_1_address0),
    .ce0(local_key_1_ce0),
    .we0(local_key_1_we0),
    .d0(local_key_0_load_reg_801),
    .q0(local_key_1_q0)
);

workload_buf_0 #(
    .DataWidth( 8 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
buf_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buf_0_address0),
    .ce0(buf_0_ce0),
    .we0(buf_0_we0),
    .d0(buf_0_d0),
    .q0(buf_0_q0),
    .address1(grp_aes256_encrypt_ecb_fu_398_buf_r_address1),
    .ce1(buf_0_ce1),
    .we1(buf_0_we1),
    .d1(grp_aes256_encrypt_ecb_fu_398_buf_r_d1),
    .q1(buf_0_q1)
);

workload_buf_0 #(
    .DataWidth( 8 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buf_1_address0),
    .ce0(buf_1_ce0),
    .we0(buf_1_we0),
    .d0(buf_1_d0),
    .q0(buf_1_q0),
    .address1(grp_aes256_encrypt_ecb_fu_398_buf_r_address1),
    .ce1(buf_1_ce1),
    .we1(buf_1_we1),
    .d1(grp_aes256_encrypt_ecb_fu_398_buf_r_d1),
    .q1(buf_1_q1)
);

aes256_encrypt_ecb grp_aes256_encrypt_ecb_fu_398(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_aes256_encrypt_ecb_fu_398_ap_start),
    .ap_done(grp_aes256_encrypt_ecb_fu_398_ap_done),
    .ap_idle(grp_aes256_encrypt_ecb_fu_398_ap_idle),
    .ap_ready(grp_aes256_encrypt_ecb_fu_398_ap_ready),
    .k_address0(grp_aes256_encrypt_ecb_fu_398_k_address0),
    .k_ce0(grp_aes256_encrypt_ecb_fu_398_k_ce0),
    .k_q0(grp_aes256_encrypt_ecb_fu_398_k_q0),
    .buf_r_address0(grp_aes256_encrypt_ecb_fu_398_buf_r_address0),
    .buf_r_ce0(grp_aes256_encrypt_ecb_fu_398_buf_r_ce0),
    .buf_r_we0(grp_aes256_encrypt_ecb_fu_398_buf_r_we0),
    .buf_r_d0(grp_aes256_encrypt_ecb_fu_398_buf_r_d0),
    .buf_r_q0(grp_aes256_encrypt_ecb_fu_398_buf_r_q0),
    .buf_r_address1(grp_aes256_encrypt_ecb_fu_398_buf_r_address1),
    .buf_r_ce1(grp_aes256_encrypt_ecb_fu_398_buf_r_ce1),
    .buf_r_we1(grp_aes256_encrypt_ecb_fu_398_buf_r_we1),
    .buf_r_d1(grp_aes256_encrypt_ecb_fu_398_buf_r_d1),
    .buf_r_q1(grp_aes256_encrypt_ecb_fu_398_buf_r_q1),
    .sum(grp_aes256_encrypt_ecb_fu_398_sum)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= 33'd1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'd1 == ap_CS_fsm_pp0_stage0) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10)) & ~(1'd0 == exitcond7_fu_422_p2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'd1 == ap_CS_fsm_state8)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'd1 == ap_CS_fsm_pp0_stage0) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10)) & (1'd0 == exitcond7_fu_422_p2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end else if (((1'd1 == ap_CS_fsm_state8) | ((1'd1 == ap_CS_fsm_pp0_stage0) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10)) & ~(1'd0 == exitcond7_fu_422_p2)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'd1 == ap_CS_fsm_state8)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'd1 == ap_CS_fsm_pp1_stage0) & ~(1'd0 == exitcond5_fu_442_p2))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'd1 == ap_CS_fsm_state12)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'd1 == ap_CS_fsm_pp1_stage0) & (1'd0 == exitcond5_fu_442_p2))) begin
            ap_enable_reg_pp1_iter1 <= 1'b1;
        end else if (((1'd1 == ap_CS_fsm_state12) | ((1'd1 == ap_CS_fsm_pp1_stage0) & ~(1'd0 == exitcond5_fu_442_p2)))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'd1 == ap_CS_fsm_pp2_stage0) & ~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & ~(1'd0 == exitcond_flatten_fu_554_p2))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'd1 == ap_CS_fsm_state25)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'd1 == ap_CS_fsm_pp2_stage0) & ~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'd0 == exitcond_flatten_fu_554_p2))) begin
            ap_enable_reg_pp2_iter1 <= 1'b1;
        end else if (((1'd1 == ap_CS_fsm_state25) | ((1'd1 == ap_CS_fsm_pp2_stage0) & ~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & ~(1'd0 == exitcond_flatten_fu_554_p2)))) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if (~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27))) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end else if ((1'd1 == ap_CS_fsm_state25)) begin
            ap_enable_reg_pp2_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if (((1'd1 == ap_CS_fsm_pp3_stage0) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & ~(1'd0 == exitcond_flatten8_fu_663_p2))) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if (((1'd1 == ap_CS_fsm_state32) & ~(1'd0 == tmp_19_fu_649_p3) & ~(1'b1 == ap_block_state32_io))) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if (((1'd1 == ap_CS_fsm_pp3_stage0) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & (1'd0 == exitcond_flatten8_fu_663_p2))) begin
            ap_enable_reg_pp3_iter1 <= 1'b1;
        end else if ((((1'd1 == ap_CS_fsm_state32) & ~(1'd0 == tmp_19_fu_649_p3) & ~(1'b1 == ap_block_state32_io)) | ((1'd1 == ap_CS_fsm_pp3_stage0) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & ~(1'd0 == exitcond_flatten8_fu_663_p2)))) begin
            ap_enable_reg_pp3_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        if (~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io))) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter3 <= 1'b0;
    end else begin
        if (~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io))) begin
            ap_enable_reg_pp3_iter3 <= ap_enable_reg_pp3_iter2;
        end else if (((1'd1 == ap_CS_fsm_state32) & ~(1'd0 == tmp_19_fu_649_p3) & ~(1'b1 == ap_block_state32_io))) begin
            ap_enable_reg_pp3_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_grp_aes256_encrypt_ecb_fu_398_ap_start <= 1'b0;
    end else begin
        if ((((1'd1 == ap_CS_fsm_state30) & (1'd0 == tmp_16_fu_635_p3)) | ((1'd1 == ap_CS_fsm_state32) & (1'd0 == tmp_19_fu_649_p3) & ~(1'b1 == ap_block_state32_io)))) begin
            ap_reg_grp_aes256_encrypt_ecb_fu_398_ap_start <= 1'b1;
        end else if ((1'b1 == grp_aes256_encrypt_ecb_fu_398_ap_ready)) begin
            ap_reg_grp_aes256_encrypt_ecb_fu_398_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_ARREADY <= 1'b0;
    end else begin
        if ((((1'd1 == ap_CS_fsm_state2) & ~(1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((1'd1 == ap_CS_fsm_state19) & ~(1'b0 == ap_sig_ioackin_gmem_ARREADY)))) begin
            ap_reg_ioackin_gmem_ARREADY <= 1'b0;
        end else if ((((1'd1 == ap_CS_fsm_state2) & (1'b1 == gmem_ARREADY)) | ((1'd1 == ap_CS_fsm_state19) & (1'b1 == gmem_ARREADY)))) begin
            ap_reg_ioackin_gmem_ARREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_AWREADY <= 1'b0;
    end else begin
        if (((1'd1 == ap_CS_fsm_state32) & ~(1'd0 == tmp_19_fu_649_p3))) begin
            if (~(1'b1 == ap_block_state32_io)) begin
                ap_reg_ioackin_gmem_AWREADY <= 1'b0;
            end else if ((1'b1 == gmem_AWREADY)) begin
                ap_reg_ioackin_gmem_AWREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_WREADY <= 1'b0;
    end else begin
        if (((1'b1 == ap_enable_reg_pp3_iter3) & (1'd0 == ap_pipeline_reg_pp3_iter2_exitcond_flatten8_reg_885))) begin
            if (~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io))) begin
                ap_reg_ioackin_gmem_WREADY <= 1'b0;
            end else if ((1'b1 == gmem_WREADY)) begin
                ap_reg_ioackin_gmem_WREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state42) & ~(1'b0 == gmem_BVALID))) begin
        i_1_reg_297 <= i_reg_829;
    end else if ((1'd1 == ap_CS_fsm_state17)) begin
        i_1_reg_297 <= 20'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp2_stage0) & ~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'b1 == ap_enable_reg_pp2_iter0) & (1'd0 == exitcond_flatten_fu_554_p2))) begin
        indvar1_reg_330 <= indvar_next1_fu_606_p2;
    end else if ((1'd1 == ap_CS_fsm_state25)) begin
        indvar1_reg_330 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state32) & ~(1'd0 == tmp_19_fu_649_p3) & ~(1'b1 == ap_block_state32_io))) begin
        indvar2_reg_387 <= 12'd0;
    end else if (((1'd1 == ap_CS_fsm_pp3_stage0) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & (1'b1 == ap_enable_reg_pp3_iter0) & (1'd0 == exitcond_flatten8_fu_663_p2))) begin
        indvar2_reg_387 <= indvar_next2_fu_715_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state32) & ~(1'd0 == tmp_19_fu_649_p3) & ~(1'b1 == ap_block_state32_io))) begin
        indvar_flatten6_reg_365 <= 13'd0;
    end else if (((1'd1 == ap_CS_fsm_pp3_stage0) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & (1'b1 == ap_enable_reg_pp3_iter0) & (1'd0 == exitcond_flatten8_fu_663_p2))) begin
        indvar_flatten6_reg_365 <= indvar_flatten_next7_fu_669_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp2_stage0) & ~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'b1 == ap_enable_reg_pp2_iter0) & (1'd0 == exitcond_flatten_fu_554_p2))) begin
        indvar_flatten_reg_308 <= indvar_flatten_next_fu_560_p2;
    end else if ((1'd1 == ap_CS_fsm_state25)) begin
        indvar_flatten_reg_308 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10)) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond7_fu_422_p2))) begin
        indvar_reg_275 <= indvar_next_fu_428_p2;
    end else if ((1'd1 == ap_CS_fsm_state8)) begin
        indvar_reg_275 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'd0 == exitcond_flatten_reg_840) & ~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)))) begin
        j_1_reg_319 <= tmp_mid2_v_v_reg_849;
    end else if ((1'd1 == ap_CS_fsm_state25)) begin
        j_1_reg_319 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state32) & ~(1'd0 == tmp_19_fu_649_p3) & ~(1'b1 == ap_block_state32_io))) begin
        j_3_reg_376 <= 2'd0;
    end else if (((1'd1 == ap_CS_fsm_pp3_stage0) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & (1'd0 == exitcond_flatten8_reg_885) & (1'b1 == ap_enable_reg_pp3_iter1))) begin
        j_3_reg_376 <= tmp_30_mid2_v_v_reg_894;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state12)) begin
        j_reg_286 <= 6'd0;
    end else if (((1'd1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter0) & (1'd0 == exitcond5_fu_442_p2))) begin
        j_reg_286 <= j_2_fu_448_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state30) & ~(1'd0 == tmp_16_fu_635_p3))) begin
        k_i1_reg_353 <= 12'd0;
    end else if ((~(1'b0 == grp_aes256_encrypt_ecb_fu_398_ap_done) & (1'd1 == ap_CS_fsm_state33))) begin
        k_i1_reg_353 <= k_1_reg_880;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state29)) begin
        k_i_reg_341 <= 12'd0;
    end else if (((1'd1 == ap_CS_fsm_state31) & ~(1'b0 == grp_aes256_encrypt_ecb_fu_398_ap_done))) begin
        k_i_reg_341 <= k_reg_871;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10)))) begin
        ap_pipeline_reg_pp0_iter1_exitcond7_reg_768 <= exitcond7_reg_768;
        ap_pipeline_reg_pp0_iter1_tmp_reg_777 <= tmp_reg_777;
        exitcond7_reg_768 <= exitcond7_fu_422_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_pp1_stage0)) begin
        ap_pipeline_reg_pp1_iter1_exitcond5_reg_782 <= exitcond5_reg_782;
        ap_pipeline_reg_pp1_iter1_tmp_6_reg_791[5 : 0] <= tmp_6_reg_791[5 : 0];
        exitcond5_reg_782 <= exitcond5_fu_442_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp2_stage0) & ~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)))) begin
        ap_pipeline_reg_pp2_iter1_tmp_12_reg_859 <= tmp_12_reg_859;
        ap_pipeline_reg_pp2_iter1_tmp_15_reg_864 <= tmp_15_reg_864;
        exitcond_flatten_reg_840 <= exitcond_flatten_fu_554_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp3_stage0) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)))) begin
        ap_pipeline_reg_pp3_iter1_exitcond_flatten8_reg_885 <= exitcond_flatten8_reg_885;
        ap_pipeline_reg_pp3_iter1_tmp_22_reg_909 <= tmp_22_reg_909;
        exitcond_flatten8_reg_885 <= exitcond_flatten8_fu_663_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io))) begin
        ap_pipeline_reg_pp3_iter2_exitcond_flatten8_reg_885 <= ap_pipeline_reg_pp3_iter1_exitcond_flatten8_reg_885;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & (1'd0 == ap_pipeline_reg_pp3_iter1_exitcond_flatten8_reg_885))) begin
        buf_load_phi_reg_924 <= buf_load_phi_fu_744_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_state1 == 1'd1) & ~(1'b0 == ap_start))) begin
        data_read_reg_757 <= data;
        gmem_addr_reg_762 <= key;
        size_read_reg_751 <= size;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state18) & ~(1'd0 == tmp_8_fu_520_p2))) begin
        gmem_addr_1_reg_834 <= data4_sum_fu_543_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state18)) begin
        i_reg_829 <= i_fu_525_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state32) & (1'd0 == tmp_19_fu_649_p3) & ~(1'b1 == ap_block_state32_io))) begin
        k_1_reg_880 <= k_1_fu_657_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state30) & (1'd0 == tmp_16_fu_635_p3))) begin
        k_reg_871 <= k_fu_643_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'd0 == exitcond5_reg_782))) begin
        local_key_0_load_reg_801 <= local_key_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state17)) begin
        num_batches_reg_821 <= num_batches_fu_509_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond7_reg_768 == 1'd0) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10))) | ((1'd1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'd0 == exitcond_flatten_reg_840) & ~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27))))) begin
        reg_409 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state16)) begin
        tmp_10_reg_806 <= tmp_5_fu_459_p2[32'd31];
        tmp_2_reg_811 <= {{p_neg_fu_472_p2[31:12]}};
        tmp_7_reg_816 <= {{tmp_5_fu_459_p2[31:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp2_stage0) & ~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'd0 == exitcond_flatten_fu_554_p2))) begin
        tmp_12_reg_859 <= tmp_12_fu_612_p1;
        tmp_15_reg_864 <= tmp_13_fu_616_p2[32'd11];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp3_stage0) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & (1'd0 == exitcond_flatten8_fu_663_p2))) begin
        tmp_21_reg_904 <= tmp_21_fu_721_p1;
        tmp_22_reg_909 <= tmp_17_fu_725_p2[32'd11];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp3_stage0) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & (1'b1 == ap_enable_reg_pp3_iter0) & (1'd0 == exitcond_flatten8_fu_663_p2))) begin
        tmp_30_mid2_v_v_reg_894 <= tmp_30_mid2_v_v_fu_695_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp1_stage0) & (1'd0 == exitcond5_fu_442_p2))) begin
        tmp_6_reg_791[5 : 0] <= tmp_6_fu_454_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp2_stage0) & ~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'b1 == ap_enable_reg_pp2_iter0) & (1'd0 == exitcond_flatten_fu_554_p2))) begin
        tmp_mid2_v_v_reg_849 <= tmp_mid2_v_v_fu_586_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_pp0_stage0) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10)) & (1'd0 == exitcond7_fu_422_p2))) begin
        tmp_reg_777 <= tmp_fu_434_p1;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state18) & (1'd0 == tmp_8_fu_520_p2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'd1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state18) & (1'd0 == tmp_8_fu_520_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_gmem_ARREADY)) begin
        ap_sig_ioackin_gmem_ARREADY = gmem_ARREADY;
    end else begin
        ap_sig_ioackin_gmem_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_gmem_AWREADY)) begin
        ap_sig_ioackin_gmem_AWREADY = gmem_AWREADY;
    end else begin
        ap_sig_ioackin_gmem_AWREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_gmem_WREADY)) begin
        ap_sig_ioackin_gmem_WREADY = gmem_WREADY;
    end else begin
        ap_sig_ioackin_gmem_WREADY = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp3_stage0) & (1'b1 == ap_enable_reg_pp3_iter1))) begin
        buf_0_address0 = tmp_18_fu_739_p1;
    end else if ((1'b1 == ap_enable_reg_pp2_iter2)) begin
        buf_0_address0 = tmp_14_fu_630_p1;
    end else if ((1'd1 == ap_CS_fsm_state31)) begin
        buf_0_address0 = grp_aes256_encrypt_ecb_fu_398_buf_r_address0;
    end else begin
        buf_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'd1 == ap_CS_fsm_pp3_stage0) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & (1'b1 == ap_enable_reg_pp3_iter1)) | (~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'b1 == ap_enable_reg_pp2_iter2)))) begin
        buf_0_ce0 = 1'b1;
    end else if ((1'd1 == ap_CS_fsm_state31)) begin
        buf_0_ce0 = grp_aes256_encrypt_ecb_fu_398_buf_r_ce0;
    end else begin
        buf_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state31)) begin
        buf_0_ce1 = grp_aes256_encrypt_ecb_fu_398_buf_r_ce1;
    end else begin
        buf_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp2_iter2)) begin
        buf_0_d0 = reg_409;
    end else if ((1'd1 == ap_CS_fsm_state31)) begin
        buf_0_d0 = grp_aes256_encrypt_ecb_fu_398_buf_r_d0;
    end else begin
        buf_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'b1 == ap_enable_reg_pp2_iter2) & (1'd0 == ap_pipeline_reg_pp2_iter1_tmp_15_reg_864))) begin
        buf_0_we0 = 1'b1;
    end else if ((1'd1 == ap_CS_fsm_state31)) begin
        buf_0_we0 = grp_aes256_encrypt_ecb_fu_398_buf_r_we0;
    end else begin
        buf_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state31)) begin
        buf_0_we1 = grp_aes256_encrypt_ecb_fu_398_buf_r_we1;
    end else begin
        buf_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp3_stage0) & (1'b1 == ap_enable_reg_pp3_iter1))) begin
        buf_1_address0 = tmp_18_fu_739_p1;
    end else if ((1'b1 == ap_enable_reg_pp2_iter2)) begin
        buf_1_address0 = tmp_14_fu_630_p1;
    end else if ((1'd1 == ap_CS_fsm_state33)) begin
        buf_1_address0 = grp_aes256_encrypt_ecb_fu_398_buf_r_address0;
    end else begin
        buf_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'd1 == ap_CS_fsm_pp3_stage0) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & (1'b1 == ap_enable_reg_pp3_iter1)) | (~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'b1 == ap_enable_reg_pp2_iter2)))) begin
        buf_1_ce0 = 1'b1;
    end else if ((1'd1 == ap_CS_fsm_state33)) begin
        buf_1_ce0 = grp_aes256_encrypt_ecb_fu_398_buf_r_ce0;
    end else begin
        buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state33)) begin
        buf_1_ce1 = grp_aes256_encrypt_ecb_fu_398_buf_r_ce1;
    end else begin
        buf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp2_iter2)) begin
        buf_1_d0 = reg_409;
    end else if ((1'd1 == ap_CS_fsm_state33)) begin
        buf_1_d0 = grp_aes256_encrypt_ecb_fu_398_buf_r_d0;
    end else begin
        buf_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'b1 == ap_enable_reg_pp2_iter2) & ~(1'd0 == ap_pipeline_reg_pp2_iter1_tmp_15_reg_864))) begin
        buf_1_we0 = 1'b1;
    end else if ((1'd1 == ap_CS_fsm_state33)) begin
        buf_1_we0 = grp_aes256_encrypt_ecb_fu_398_buf_r_we0;
    end else begin
        buf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state33)) begin
        buf_1_we1 = grp_aes256_encrypt_ecb_fu_398_buf_r_we1;
    end else begin
        buf_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_gmem_ARREADY)) begin
        if ((1'd1 == ap_CS_fsm_state19)) begin
            gmem_ARADDR = gmem_addr_1_reg_834;
        end else if ((1'd1 == ap_CS_fsm_state2)) begin
            gmem_ARADDR = gmem_addr_reg_762;
        end else begin
            gmem_ARADDR = 'bx;
        end
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_gmem_ARREADY)) begin
        if ((1'd1 == ap_CS_fsm_state19)) begin
            gmem_ARLEN = 32'd4096;
        end else if ((1'd1 == ap_CS_fsm_state2)) begin
            gmem_ARLEN = 32'd32;
        end else begin
            gmem_ARLEN = 'bx;
        end
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((1'd1 == ap_CS_fsm_state2) & (1'b0 == ap_reg_ioackin_gmem_ARREADY)) | ((1'd1 == ap_CS_fsm_state19) & (1'b0 == ap_reg_ioackin_gmem_ARREADY)))) begin
        gmem_ARVALID = 1'b1;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state32) & ~(1'd0 == tmp_19_fu_649_p3) & (1'b0 == ap_reg_ioackin_gmem_AWREADY))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state42) & ~(1'b0 == gmem_BVALID))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond7_reg_768 == 1'd0) & ~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10))) | ((1'd1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'd0 == exitcond_flatten_reg_840) & ~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27))))) begin
        gmem_RREADY = 1'b1;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp3_iter3) & (1'd0 == ap_pipeline_reg_pp3_iter2_exitcond_flatten8_reg_885) & (1'b0 == ap_reg_ioackin_gmem_WREADY))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state2) | (1'd1 == ap_CS_fsm_state19))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state32) & ~(1'd0 == tmp_19_fu_649_p3))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state42)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((1'd1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond7_reg_768 == 1'd0)) | ((1'd1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'd0 == exitcond_flatten_reg_840)))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp3_iter3) & (1'd0 == ap_pipeline_reg_pp3_iter2_exitcond_flatten8_reg_885))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state33)) begin
        grp_aes256_encrypt_ecb_fu_398_buf_r_q0 = buf_1_q0;
    end else if ((1'd1 == ap_CS_fsm_state31)) begin
        grp_aes256_encrypt_ecb_fu_398_buf_r_q0 = buf_0_q0;
    end else begin
        grp_aes256_encrypt_ecb_fu_398_buf_r_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state33)) begin
        grp_aes256_encrypt_ecb_fu_398_buf_r_q1 = buf_1_q1;
    end else if ((1'd1 == ap_CS_fsm_state31)) begin
        grp_aes256_encrypt_ecb_fu_398_buf_r_q1 = buf_0_q1;
    end else begin
        grp_aes256_encrypt_ecb_fu_398_buf_r_q1 = 'bx;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state33)) begin
        grp_aes256_encrypt_ecb_fu_398_k_q0 = local_key_1_q0;
    end else if ((1'd1 == ap_CS_fsm_state31)) begin
        grp_aes256_encrypt_ecb_fu_398_k_q0 = local_key_0_q0;
    end else begin
        grp_aes256_encrypt_ecb_fu_398_k_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state33)) begin
        grp_aes256_encrypt_ecb_fu_398_sum = k_i1_reg_353;
    end else if ((1'd1 == ap_CS_fsm_state31)) begin
        grp_aes256_encrypt_ecb_fu_398_sum = k_i_reg_341;
    end else begin
        grp_aes256_encrypt_ecb_fu_398_sum = 'bx;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'd0 == exitcond_flatten_reg_840))) begin
        j_1_phi_fu_323_p4 = tmp_mid2_v_v_reg_849;
    end else begin
        j_1_phi_fu_323_p4 = j_1_reg_319;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp3_stage0) & (1'd0 == exitcond_flatten8_reg_885) & (1'b1 == ap_enable_reg_pp3_iter1))) begin
        j_3_phi_fu_380_p4 = tmp_30_mid2_v_v_reg_894;
    end else begin
        j_3_phi_fu_380_p4 = j_3_reg_376;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter0))) begin
        local_key_0_address0 = tmp_6_fu_454_p1;
    end else if ((1'b1 == ap_enable_reg_pp0_iter2)) begin
        local_key_0_address0 = tmp_4_fu_438_p1;
    end else if ((1'd1 == ap_CS_fsm_state31)) begin
        local_key_0_address0 = grp_aes256_encrypt_ecb_fu_398_k_address0;
    end else begin
        local_key_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'd1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter0)) | (~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10)) & (1'b1 == ap_enable_reg_pp0_iter2)))) begin
        local_key_0_ce0 = 1'b1;
    end else if ((1'd1 == ap_CS_fsm_state31)) begin
        local_key_0_ce0 = grp_aes256_encrypt_ecb_fu_398_k_ce0;
    end else begin
        local_key_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10)) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd0 == ap_pipeline_reg_pp0_iter1_exitcond7_reg_768))) begin
        local_key_0_we0 = 1'b1;
    end else begin
        local_key_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp1_iter2)) begin
        local_key_1_address0 = ap_pipeline_reg_pp1_iter1_tmp_6_reg_791;
    end else if ((1'd1 == ap_CS_fsm_state33)) begin
        local_key_1_address0 = grp_aes256_encrypt_ecb_fu_398_k_address0;
    end else begin
        local_key_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp1_iter2)) begin
        local_key_1_ce0 = 1'b1;
    end else if ((1'd1 == ap_CS_fsm_state33)) begin
        local_key_1_ce0 = grp_aes256_encrypt_ecb_fu_398_k_ce0;
    end else begin
        local_key_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp1_iter2) & (1'd0 == ap_pipeline_reg_pp1_iter1_exitcond5_reg_782))) begin
        local_key_1_we0 = 1'b1;
    end else begin
        local_key_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        33'd1 : begin
            if (~(1'b0 == ap_start)) begin
                ap_NS_fsm = 33'd2;
            end else begin
                ap_NS_fsm = 33'd1;
            end
        end
        33'd2 : begin
            if (~(1'b0 == ap_sig_ioackin_gmem_ARREADY)) begin
                ap_NS_fsm = 33'd4;
            end else begin
                ap_NS_fsm = 33'd2;
            end
        end
        33'd4 : begin
            ap_NS_fsm = 33'd8;
        end
        33'd8 : begin
            ap_NS_fsm = 33'd16;
        end
        33'd16 : begin
            ap_NS_fsm = 33'd32;
        end
        33'd32 : begin
            ap_NS_fsm = 33'd64;
        end
        33'd64 : begin
            ap_NS_fsm = 33'd128;
        end
        33'd128 : begin
            ap_NS_fsm = 33'd256;
        end
        33'd256 : begin
            if ((~(~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10)) & (1'b1 == ap_enable_reg_pp0_iter2) & ~(1'b1 == ap_enable_reg_pp0_iter1)) & ~(~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10)) & (1'b1 == ap_enable_reg_pp0_iter0) & ~(1'd0 == exitcond7_fu_422_p2) & ~(1'b1 == ap_enable_reg_pp0_iter1)))) begin
                ap_NS_fsm = 33'd256;
            end else if (((~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10)) & (1'b1 == ap_enable_reg_pp0_iter2) & ~(1'b1 == ap_enable_reg_pp0_iter1)) | (~((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10)) & (1'b1 == ap_enable_reg_pp0_iter0) & ~(1'd0 == exitcond7_fu_422_p2) & ~(1'b1 == ap_enable_reg_pp0_iter1)))) begin
                ap_NS_fsm = 33'd512;
            end else begin
                ap_NS_fsm = 33'd256;
            end
        end
        33'd512 : begin
            ap_NS_fsm = 33'd1024;
        end
        33'd1024 : begin
            if ((~((1'b1 == ap_enable_reg_pp1_iter2) & ~(1'b1 == ap_enable_reg_pp1_iter1)) & ~((1'b1 == ap_enable_reg_pp1_iter0) & ~(1'd0 == exitcond5_fu_442_p2) & ~(1'b1 == ap_enable_reg_pp1_iter1)))) begin
                ap_NS_fsm = 33'd1024;
            end else if (((1'b1 == ap_enable_reg_pp1_iter0) & ~(1'd0 == exitcond5_fu_442_p2) & ~(1'b1 == ap_enable_reg_pp1_iter1))) begin
                ap_NS_fsm = 33'd2048;
            end else begin
                ap_NS_fsm = 33'd2048;
            end
        end
        33'd2048 : begin
            ap_NS_fsm = 33'd4096;
        end
        33'd4096 : begin
            ap_NS_fsm = 33'd8192;
        end
        33'd8192 : begin
            if ((1'd0 == tmp_8_fu_520_p2)) begin
                ap_NS_fsm = 33'd1;
            end else begin
                ap_NS_fsm = 33'd16384;
            end
        end
        33'd16384 : begin
            if (~(1'b0 == ap_sig_ioackin_gmem_ARREADY)) begin
                ap_NS_fsm = 33'd32768;
            end else begin
                ap_NS_fsm = 33'd16384;
            end
        end
        33'd32768 : begin
            ap_NS_fsm = 33'd65536;
        end
        33'd65536 : begin
            ap_NS_fsm = 33'd131072;
        end
        33'd131072 : begin
            ap_NS_fsm = 33'd262144;
        end
        33'd262144 : begin
            ap_NS_fsm = 33'd524288;
        end
        33'd524288 : begin
            ap_NS_fsm = 33'd1048576;
        end
        33'd1048576 : begin
            ap_NS_fsm = 33'd2097152;
        end
        33'd2097152 : begin
            if ((~(~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'b1 == ap_enable_reg_pp2_iter2) & ~(1'b1 == ap_enable_reg_pp2_iter1)) & ~(~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'b1 == ap_enable_reg_pp2_iter0) & ~(1'd0 == exitcond_flatten_fu_554_p2) & ~(1'b1 == ap_enable_reg_pp2_iter1)))) begin
                ap_NS_fsm = 33'd2097152;
            end else if (((~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'b1 == ap_enable_reg_pp2_iter2) & ~(1'b1 == ap_enable_reg_pp2_iter1)) | (~((1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_block_state27)) & (1'b1 == ap_enable_reg_pp2_iter0) & ~(1'd0 == exitcond_flatten_fu_554_p2) & ~(1'b1 == ap_enable_reg_pp2_iter1)))) begin
                ap_NS_fsm = 33'd4194304;
            end else begin
                ap_NS_fsm = 33'd2097152;
            end
        end
        33'd4194304 : begin
            ap_NS_fsm = 33'd8388608;
        end
        33'd8388608 : begin
            if (~(1'd0 == tmp_16_fu_635_p3)) begin
                ap_NS_fsm = 33'd33554432;
            end else begin
                ap_NS_fsm = 33'd16777216;
            end
        end
        33'd16777216 : begin
            if (~(1'b0 == grp_aes256_encrypt_ecb_fu_398_ap_done)) begin
                ap_NS_fsm = 33'd8388608;
            end else begin
                ap_NS_fsm = 33'd16777216;
            end
        end
        33'd33554432 : begin
            if ((~(1'd0 == tmp_19_fu_649_p3) & ~(1'b1 == ap_block_state32_io))) begin
                ap_NS_fsm = 33'd134217728;
            end else if (((1'd0 == tmp_19_fu_649_p3) & ~(1'b1 == ap_block_state32_io))) begin
                ap_NS_fsm = 33'd67108864;
            end else begin
                ap_NS_fsm = 33'd33554432;
            end
        end
        33'd67108864 : begin
            if (~(1'b0 == grp_aes256_encrypt_ecb_fu_398_ap_done)) begin
                ap_NS_fsm = 33'd33554432;
            end else begin
                ap_NS_fsm = 33'd67108864;
            end
        end
        33'd134217728 : begin
            if ((~((1'b1 == ap_enable_reg_pp3_iter3) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & ~(1'b1 == ap_enable_reg_pp3_iter2)) & ~(~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & (1'b1 == ap_enable_reg_pp3_iter0) & ~(1'd0 == exitcond_flatten8_fu_663_p2) & ~(1'b1 == ap_enable_reg_pp3_iter1)))) begin
                ap_NS_fsm = 33'd134217728;
            end else if ((((1'b1 == ap_enable_reg_pp3_iter3) & ~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & ~(1'b1 == ap_enable_reg_pp3_iter2)) | (~((1'b1 == ap_enable_reg_pp3_iter3) & (1'b1 == ap_block_state37_io)) & (1'b1 == ap_enable_reg_pp3_iter0) & ~(1'd0 == exitcond_flatten8_fu_663_p2) & ~(1'b1 == ap_enable_reg_pp3_iter1)))) begin
                ap_NS_fsm = 33'd268435456;
            end else begin
                ap_NS_fsm = 33'd134217728;
            end
        end
        33'd268435456 : begin
            ap_NS_fsm = 33'd536870912;
        end
        33'd536870912 : begin
            ap_NS_fsm = 33'd1073741824;
        end
        33'd1073741824 : begin
            ap_NS_fsm = 33'd2147483648;
        end
        33'd2147483648 : begin
            ap_NS_fsm = 33'd4294967296;
        end
        33'd4294967296 : begin
            if (~(1'b0 == gmem_BVALID)) begin
                ap_NS_fsm = 33'd8192;
            end else begin
                ap_NS_fsm = 33'd4294967296;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state10 = ((exitcond7_reg_768 == 1'd0) & (1'b0 == gmem_RVALID));
end

always @ (*) begin
    ap_block_state27 = ((1'd0 == exitcond_flatten_reg_840) & (1'b0 == gmem_RVALID));
end

always @ (*) begin
    ap_block_state32_io = (~(1'd0 == tmp_19_fu_649_p3) & (1'b0 == ap_sig_ioackin_gmem_AWREADY));
end

always @ (*) begin
    ap_block_state37_io = ((1'd0 == ap_pipeline_reg_pp3_iter2_exitcond_flatten8_reg_885) & (1'b0 == ap_sig_ioackin_gmem_WREADY));
end

always @ (*) begin
    ap_enable_pp0 = ((ap_enable_reg_pp0_iter0 == 1'b1) | (ap_enable_reg_pp0_iter1 == 1'b1) | (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_enable_pp1 = ((ap_enable_reg_pp1_iter0 == 1'b1) | (ap_enable_reg_pp1_iter1 == 1'b1) | (ap_enable_reg_pp1_iter2 == 1'b1));
end

always @ (*) begin
    ap_enable_pp2 = ((ap_enable_reg_pp2_iter0 == 1'b1) | (ap_enable_reg_pp2_iter1 == 1'b1) | (ap_enable_reg_pp2_iter2 == 1'b1));
end

always @ (*) begin
    ap_enable_pp3 = ((ap_enable_reg_pp3_iter0 == 1'b1) | (ap_enable_reg_pp3_iter1 == 1'b1) | (ap_enable_reg_pp3_iter2 == 1'b1) | (ap_enable_reg_pp3_iter3 == 1'b1));
end

assign buf_load_phi_fu_744_p3 = ((ap_pipeline_reg_pp3_iter1_tmp_22_reg_909[0:0] === 1'b1) ? buf_1_q0 : buf_0_q0);

assign data4_sum_fu_543_p2 = (tmp_9_fu_539_p1 + data_read_reg_757);

assign exitcond1_fu_675_p2 = ((indvar2_reg_387 == 12'd2048) ? 1'b1 : 1'b0);

assign exitcond5_fu_442_p2 = ((j_reg_286 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond7_fu_422_p2 = ((indvar_reg_275 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond_flatten8_fu_663_p2 = ((indvar_flatten6_reg_365 == 13'd4096) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_554_p2 = ((indvar_flatten_reg_308 == 13'd4096) ? 1'b1 : 1'b0);

assign exitcond_fu_566_p2 = ((indvar1_reg_330 == 12'd2048) ? 1'b1 : 1'b0);

assign grp_aes256_encrypt_ecb_fu_398_ap_start = ap_reg_grp_aes256_encrypt_ecb_fu_398_ap_start;

assign i_1_cast_fu_516_p1 = i_1_reg_297;

assign i_fu_525_p2 = (i_1_reg_297 + 20'd1);

assign indvar1_mid2_fu_572_p3 = ((exitcond_fu_566_p2[0:0] === 1'b1) ? 12'd0 : indvar1_reg_330);

assign indvar2_mid2_fu_681_p3 = ((exitcond1_fu_675_p2[0:0] === 1'b1) ? 12'd0 : indvar2_reg_387);

assign indvar_flatten_next7_fu_669_p2 = (indvar_flatten6_reg_365 + 13'd1);

assign indvar_flatten_next_fu_560_p2 = (indvar_flatten_reg_308 + 13'd1);

assign indvar_next1_fu_606_p2 = (12'd1 + indvar1_mid2_fu_572_p3);

assign indvar_next2_fu_715_p2 = (12'd1 + indvar2_mid2_fu_681_p3);

assign indvar_next_fu_428_p2 = (indvar_reg_275 + 6'd1);

assign j_2_fu_448_p2 = (j_reg_286 + 6'd1);

assign j_4_fu_689_p2 = (2'd1 + j_3_phi_fu_380_p4);

assign j_s_fu_580_p2 = (2'd1 + j_1_phi_fu_323_p4);

assign k_1_fu_657_p2 = (k_i1_reg_353 + 12'd16);

assign k_fu_643_p2 = (k_i_reg_341 + 12'd16);

assign num_batches_fu_509_p3 = ((tmp_10_reg_806[0:0] === 1'b1) ? p_neg_t_fu_500_p2 : p_lshr_f_cast_fu_506_p1);

assign p_lshr_cast_fu_497_p1 = tmp_2_reg_811;

assign p_lshr_f_cast_fu_506_p1 = tmp_7_reg_816;

assign p_neg_fu_472_p2 = ($signed(32'd4294963201) - $signed(size_read_reg_751));

assign p_neg_t_fu_500_p2 = (21'd0 - p_lshr_cast_fu_497_p1);

assign tmp_11_fu_594_p1 = tmp_mid2_v_v_fu_586_p3[0:0];

assign tmp_12_fu_612_p1 = indvar1_mid2_fu_572_p3[10:0];

assign tmp_13_fu_616_p2 = (indvar1_mid2_fu_572_p3 + tmp_mid2_fu_598_p3);

assign tmp_14_fu_630_p1 = ap_pipeline_reg_pp2_iter1_tmp_12_reg_859;

assign tmp_16_fu_635_p3 = k_i_reg_341[32'd11];

assign tmp_17_fu_725_p2 = (indvar2_mid2_fu_681_p3 + tmp_30_mid2_fu_707_p3);

assign tmp_18_fu_739_p1 = tmp_21_reg_904;

assign tmp_19_fu_649_p3 = k_i1_reg_353[32'd11];

assign tmp_20_fu_703_p1 = tmp_30_mid2_v_v_fu_695_p3[0:0];

assign tmp_21_fu_721_p1 = indvar2_mid2_fu_681_p3[10:0];

assign tmp_30_mid2_fu_707_p3 = {{tmp_20_fu_703_p1}, {11'd0}};

assign tmp_30_mid2_v_v_fu_695_p3 = ((exitcond1_fu_675_p2[0:0] === 1'b1) ? j_4_fu_689_p2 : j_3_phi_fu_380_p4);

assign tmp_4_fu_438_p1 = ap_pipeline_reg_pp0_iter1_tmp_reg_777;

assign tmp_5_fu_459_p2 = (size_read_reg_751 + 32'd4095);

assign tmp_6_fu_454_p1 = j_reg_286;

assign tmp_8_fu_520_p2 = (($signed(i_1_cast_fu_516_p1) < $signed(num_batches_reg_821)) ? 1'b1 : 1'b0);

assign tmp_9_fu_539_p1 = tmp_s_fu_531_p3;

assign tmp_fu_434_p1 = indvar_reg_275[4:0];

assign tmp_mid2_fu_598_p3 = {{tmp_11_fu_594_p1}, {11'd0}};

assign tmp_mid2_v_v_fu_586_p3 = ((exitcond_fu_566_p2[0:0] === 1'b1) ? j_s_fu_580_p2 : j_1_phi_fu_323_p4);

assign tmp_s_fu_531_p3 = {{i_1_reg_297}, {12'd0}};

always @ (posedge ap_clk) begin
    tmp_6_reg_791[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    ap_pipeline_reg_pp1_iter1_tmp_6_reg_791[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //workload
